name: 'delete workflowlogs'
description: 'delete workflow'
inputs:
  token:
    description: 'authenticated token'
    required: true
  ownerRepo:
    description: 'Set a slash-separated value for owner and repository.'
    required: true
  existsCount:
    description: 'Specifies the number left in the uploaded artifacts.'
    required: false
    default: "5"
runs:
  using: node16
  main: dist/index.js
